#!/bin/bash

function parse_git_branch() {
   inside_git_repo="$(git rev-parse --is-inside-work-tree 2>/dev/null)"
   if [[ $inside_git_repo ]]; then
      echo "($(git rev-parse --abbrev-ref HEAD 2> /dev/null))"
   fi;
   #git rev-parse --git-dir 2> /dev/null;
   #git rev-parse --abbrev-ref HEAD 2> /dev/null | sed -e 's/.*\/\(.*\)/\1/'
}

current_branch="$(parse_git_branch)";

gl current_branch master
